# -*- coding: utf-8 -*-
"""TelcomChurnAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgGCRsL6bXsRr4rNxXXvTNdTzs5HiEf0
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/1730285168-TelecomCustomerChurn.csv")

df.head()

df.shape

df["Churn"].value_counts()
#to check if dataset is balanced or not-> accordingly ml technique is applied
#No is dominating so not balanced

df.info()

df.describe() #for numerical interpretations

df.isnull()

df.isnull().sum()

df.duplicated().sum()

list(df.columns)

y=df['Churn']
X=df.drop(['customerID','Churn'],axis=1)

X.head()

y.head()

y.value_counts()
#imbalanced dataset

from imblearn.over_sampling import RandomOverSampler
#imbalance learn

ros=RandomOverSampler()

X,y=ros.fit_resample(X,y)
#balances X and y

X.head()

y.value_counts()

#ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder()

X=oe.fit_transform(X)

X

#train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

#select mode
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()

rfc.fit(X_train,y_train)

y_pred=rfc.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))